"""
Game definitions for all supported FromSoftware co-op mods.
"""

import os

GAME_DEFINITIONS = {
    "ac6": {
        "name": "Armored Core 6",
        "steam_app_id": 1888160,
        "steam_folder": "ARMORED CORE VI FIRES OF RUBICON",
        "config_relative": os.path.join("Game", "AC6Coop", "ac6_coop_settings.ini"),
        "mod_extract_relative": "Game",
        "save_appdata_folder": "ArmoredCore6",
        "save_prefix": "AC60000",
        "base_ext": ".sl2",
        "coop_ext": ".co2",
        "mod_name": "AC6 Seamless Co-op",
        "nexus_domain": "armoredcore6firesofrubicon",
        "nexus_mod_id": 3,
        "nexus_url": "https://www.nexusmods.com/armoredcore6firesofrubicon/mods/3",
        "zip_pattern": r"armored\s*core.*co-?op.*\.zip$",
        "launcher_relative": os.path.join("Game", "ac6_for_coop_launcher.exe"),
        "mod_marker_relative": os.path.join("Game", "AC6Coop"),
        "me3_game_name": "armoredcore6",
        "defaults": {
            "enemy_health_scaling": "100",
            "enemy_posture_scaling": "100",
            "enemy_damage_scaling": "0",
            "display_party_members": "1",
            "enable_friendly_fire": "0",
            "auto_mission_failure_on_death": "0",
            "allow_evil_guest": "0",
            "mod_language_override": "",
        },
    },
    "dsr": {
        "name": "Dark Souls Remastered",
        "steam_app_id": 570940,
        "steam_folder": "DARK SOULS REMASTERED",
        "config_relative": os.path.join("SeamlessCoop", "ds1sc_settings.ini"),
        "mod_extract_relative": "",
        "save_appdata_folder": "DarkSoulsRemastered",
        "save_prefix": "DSR0000",
        "base_ext": ".sl2",
        "coop_ext": ".co2",
        "mod_name": "DSR Seamless Co-op",
        "nexus_domain": "darksoulsremastered",
        "nexus_mod_id": 899,
        "nexus_url": "https://www.nexusmods.com/darksoulsremastered/mods/899",
        "zip_pattern": r"ds1.*seamless.*co-?op.*\.zip$",
        "launcher_relative": os.path.join("SeamlessCoop", "ds1sc_launcher.exe"),
        "mod_marker_relative": "SeamlessCoop",
        "me3_game_name": "darksoulsremastered",
        "defaults": {
            "allow_invaders": "1",
            "death_debuffs": "1",
            "overhead_player_display": "2",
            "skip_intros": "0",
            "enemy_health_scaling": "35",
            "enemy_damage_scaling": "0",
            "enemy_posture_scaling": "15",
            "boss_health_scaling": "100",
            "boss_damage_scaling": "0",
            "boss_posture_scaling": "20",
            "cooppassword": "",
            "save_file_extension": "co2",
            "mod_language_override": "",
        },
    },
    "ds3": {
        "name": "Dark Souls III",
        "steam_app_id": 374320,
        "steam_folder": "DARK SOULS III",
        "config_relative": os.path.join("Game", "SeamlessCoop", "ds3sc_settings.ini"),
        "mod_extract_relative": "Game",
        "save_appdata_folder": "DarkSoulsIII",
        "save_prefix": "DS30000",
        "base_ext": ".sl2",
        "coop_ext": ".co2",
        "mod_name": "DS3 Seamless Co-op",
        "nexus_domain": "darksouls3",
        "nexus_mod_id": 1895,
        "nexus_url": "https://www.nexusmods.com/darksouls3/mods/1895",
        "zip_pattern": r"ds3.*seamless.*co-?op.*\.zip$",
        "launcher_relative": os.path.join("Game", "SeamlessCoop", "ds3sc_launcher.exe"),
        "mod_marker_relative": os.path.join("Game", "SeamlessCoop"),
        "me3_game_name": "darksouls3",
        "defaults": {
            "allow_invaders": "1",
            "death_debuffs": "1",
            "overhead_player_display": "2",
            "skip_intros": "1",
            "sync_progress_as_guest": "1",
            "game_boot_volume": "5",
            "enemy_health_scaling": "35",
            "enemy_damage_scaling": "0",
            "enemy_posture_scaling": "15",
            "boss_health_scaling": "100",
            "boss_damage_scaling": "0",
            "boss_posture_scaling": "20",
            "cooppassword": "",
            "save_file_extension": "co2",
            "mod_language_override": "",
        },
    },
    "er": {
        "name": "Elden Ring",
        "steam_app_id": 1245620,
        "steam_folder": "ELDEN RING",
        "config_relative": os.path.join("Game", "SeamlessCoop", "ersc_settings.ini"),
        "mod_extract_relative": "Game",
        "save_appdata_folder": "EldenRing",
        "save_prefix": "ER0000",
        "base_ext": ".sl2",
        "coop_ext": ".co2",
        "mod_name": "Elden Ring Seamless Co-op",
        "nexus_domain": "eldenring",
        "nexus_mod_id": 510,
        "nexus_url": "https://www.nexusmods.com/eldenring/mods/510",
        "zip_pattern": r"^(seamless|er\s+seamless|eldenring\s+seamless|elden\s+ring\s+seamless)\s+co-?op.*\.zip$",
        "launcher_relative": os.path.join("Game", "SeamlessCoop", "ersc_launcher.exe"),
        "mod_marker_relative": os.path.join("Game", "SeamlessCoop"),
        "me3_game_name": "eldenring",
        "defaults": {
            "allow_invaders": "1",
            "death_debuffs": "1",
            "allow_summons": "1",
            "overhead_player_display": "0",
            "skip_splash_screens": "1",
            "enemy_health_scaling": "35",
            "enemy_damage_scaling": "0",
            "enemy_posture_scaling": "15",
            "boss_health_scaling": "100",
            "boss_damage_scaling": "0",
            "boss_posture_scaling": "20",
            "cooppassword": "",
            "save_file_extension": "co2",
            "mod_language_override": "",
        },
    },
    "ern": {
        "name": "Elden Ring Nightreign",
        "steam_app_id": 2622380,
        "steam_folder": "ELDEN RING NIGHTREIGN",
        "config_relative": os.path.join("Game", "SeamlessCoop", "nrsc_settings.ini"),
        "mod_extract_relative": "Game",
        "save_appdata_folder": "EldenRingNightreign",
        "save_prefix": "ERN0000",
        "base_ext": ".sl2",
        "coop_ext": ".co2",
        "mod_name": "ER Nightreign Seamless Co-op",
        "nexus_domain": "eldenringnightreign",
        "nexus_mod_id": 3,
        "nexus_url": "https://www.nexusmods.com/eldenringnightreign/mods/3",
        "zip_pattern": r"nightreign.*seamless.*co-?op.*\.zip$|ern.*seamless.*co-?op.*\.zip$",
        "launcher_relative": os.path.join("Game", "SeamlessCoop", "nrsc_launcher.exe"),
        "mod_marker_relative": os.path.join("Game", "SeamlessCoop"),
        "me3_game_name": "nightreign",
        "defaults": {
            "allow_invaders": "1",
            "death_debuffs": "1",
            "allow_summons": "1",
            "overhead_player_display": "0",
            "skip_splash_screens": "1",
            "enemy_health_scaling": "35",
            "enemy_damage_scaling": "0",
            "enemy_posture_scaling": "15",
            "boss_health_scaling": "100",
            "boss_damage_scaling": "0",
            "boss_posture_scaling": "20",
            "cooppassword": "",
            "save_file_extension": "co2",
            "mod_language_override": "",
        },
    },
    "sekiro": {
        "name": "Sekiro: Shadows Die Twice",
        "steam_app_id": 814380,
        "steam_folder": "Sekiro",
        "config_relative": "",
        "mod_extract_relative": "",
        "save_appdata_folder": "Sekiro",
        "save_prefix": "S0000",
        "base_ext": ".sl2",
        "coop_ext": "",
        "mod_name": "",
        "nexus_domain": "sekiro",
        "nexus_mod_id": 0,
        "nexus_url": "",
        "zip_pattern": r"",
        "launcher_relative": "",
        "mod_marker_relative": "",
        "me3_game_name": "sekiro",
        "defaults": {},
    },
}

# Steam app IDs for player count lookups
STEAM_APP_IDS = {gid: gdef["steam_app_id"] for gid, gdef in GAME_DEFINITIONS.items()}
